<?php

namespace Database\Seeders;

use App\Enums\SupportTier;
use App\Enums\TicketPriority;
use App\Enums\TicketStatus;
use App\Models\Category;
use App\Models\Ticket;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

/**
 * Optional sample data for local demos and manual testing. Not run in
 * production. Invoke explicitly with:
 *   php artisan db:seed --class=DemoTicketSeeder
 */
class DemoTicketSeeder extends Seeder
{
    public function run(): void
    {
        if (app()->environment('production')) {
            $this->command?->warn('DemoTicketSeeder skipped in production.');

            return;
        }

        $l1 = User::where('email', 'l1@example.com')->first();
        $l2 = User::where('email', 'l2@example.com')->first();
        $categories = Category::pluck('id')->all();

        if (! $l1 || ! $l2 || empty($categories)) {
            $this->command?->warn('Run RoleSeeder/UserSeeder/CategorySeeder first.');

            return;
        }

        $samples = [
            ['Laptop will not power on', TicketPriority::High, TicketStatus::Open, SupportTier::L1],
            ['VPN disconnects every few minutes', TicketPriority::Medium, TicketStatus::InProgress, SupportTier::L1],
            ['Cannot access shared drive', TicketPriority::Medium, TicketStatus::Pending, SupportTier::L1],
            ['Outlook crashes on startup', TicketPriority::High, TicketStatus::InProgress, SupportTier::L2],
            ['Suspicious phishing email reported', TicketPriority::Urgent, TicketStatus::Resolved, SupportTier::L2],
            ['Request new monitor', TicketPriority::Low, TicketStatus::Closed, SupportTier::L1],
            ['Password reset for finance app', TicketPriority::Medium, TicketStatus::Resolved, SupportTier::L1],
            ['Printer on 3rd floor jams constantly', TicketPriority::Low, TicketStatus::Open, SupportTier::L1],
        ];

        foreach ($samples as $i => [$title, $priority, $status, $tier]) {
            $createdAt = Carbon::now()->subDays(20 - $i)->subHours(random_int(0, 12));
            $resolvedAt = in_array($status, [TicketStatus::Resolved, TicketStatus::Closed], true)
                ? (clone $createdAt)->addHours(random_int(3, 72))
                : null;

            $ticket = Ticket::create([
                'title' => $title,
                'description' => 'Demo ticket generated by DemoTicketSeeder. '.$title.'.',
                'category_id' => $categories[array_rand($categories)],
                'priority' => $priority,
                'status' => $status,
                'support_tier' => $tier,
                'created_by' => $l1->id,
                'assigned_to' => $tier === SupportTier::L2 ? $l2->id : ($i % 2 ? $l1->id : null),
                'resolution' => $resolvedAt ? 'Resolved during demo seeding.' : null,
                'escalated_at' => $tier === SupportTier::L2 ? (clone $createdAt)->addHours(2) : null,
                'resolved_at' => $resolvedAt,
                'closed_at' => $status === TicketStatus::Closed ? $resolvedAt?->copy()->addHours(6) : null,
            ]);

            // Backdate the timestamps so the dashboard/report charts have history.
            $ticket->forceFill([
                'created_at' => $createdAt,
                'updated_at' => $resolvedAt ?? $createdAt,
            ])->saveQuietly();

            $ticket->activities()->create([
                'user_id' => $l1->id,
                'event' => 'created',
                'description' => 'Ticket created',
                'created_at' => $createdAt,
            ]);
        }

        $this->command?->info('Created '.count($samples).' demo tickets.');
    }
}
